name: cache

on:
  schedule:
    - cron: "0 13 * * 0"

  workflow_dispatch:

jobs:
  cache:
    uses: ./.github/workflows/build.yml

    permissions:
      contents: read

    secrets:
      YOCTOCACHE_KNOWN_HOST: ${{ secrets.YOCTOCACHE_KNOWN_HOST }}
      YOCTOCACHE_DEPLOY_KEY: ${{ secrets.YOCTOCACHE_DEPLOY_KEY }}
      YOCTOCACHE_DEST: ${{ secrets.YOCTOCACHE_DEST }}
      YOCTOCACHE_PORT: ${{ secrets.YOCTOCACHE_PORT }}

    with:
      sdk: true
      cache: true
